// src/context/Reservas/ActionsTypes.js

const ReservasTypes = {
  SET_LOADING: "RESERVAS_SET_LOADING",
  SET_ERROR: "RESERVAS_SET_ERROR",
  SET_RESERVAS: "RESERVAS_SET_RESERVAS",
  SET_RESERVAS_USUARIO: "RESERVAS_SET_RESERVAS_USUARIO",
  ADD_RESERVA: "RESERVAS_ADD_RESERVA",
  UPDATE_RESERVA: "RESERVAS_UPDATE_RESERVA",
};

export default ReservasTypes;
