export const USUARIOS_ACTIONS = {
    LISTAR: 'LISTAR_USUARIOS',
    OBTENER: 'OBTENER_USUARIO',
    REGISTRAR: 'REGISTRAR_USUARIO',
    ACTUALIZAR: 'ACTUALIZAR_USUARIO',
    TIPOS_USUARIO: 'TIPOS_USUARIO',
    ERROR: 'USUARIOS_ERROR'
};
