export const GET_CARGOS_MANTENIMIENTO = "GET_CARGOS_MANTENIMIENTO";
export const GET_CARGOS_MANTENIMIENTO_USER = "GET_CARGOS_MANTENIMIENTO_USER";
export const GET_CARGOS_SERVICIOS = "GET_CARGOS_SERVICIOS";
export const GET_CARGOS_SERVICIOS_USER = "GET_CARGOS_SERVICIOS_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";