// src/context/Servicios/ActionsTypes.js

export const SERVICIOS_SET_LOADING = "SERVICIOS_SET_LOADING";
export const SERVICIOS_SET_ERROR = "SERVICIOS_SET_ERROR";

export const SERVICIOS_SET_TIPOS = "SERVICIOS_SET_TIPOS";
export const SERVICIOS_SET_CATALOGO = "SERVICIOS_SET_CATALOGO";
export const SERVICIOS_SET_PERSONAL = "SERVICIOS_SET_PERSONAL";

export const SERVICIOS_SET_SOLICITUDES = "SERVICIOS_SET_SOLICITUDES";
export const SERVICIOS_SET_SOLICITUD_ACTUAL = "SERVICIOS_SET_SOLICITUD_ACTUAL";

export const SERVICIOS_SET_CARGOS_SERVICIOS = "SERVICIOS_SET_CARGOS_SERVICIOS";
export const SERVICIOS_SET_CARGOS_MANT = "SERVICIOS_SET_CARGOS_MANT";
