// src/context/Amenidades/ActionsTypes.js
export const AMENIDADES_LOADING = "AMENIDADES_LOADING";
export const AMENIDADES_ERROR = "AMENIDADES_ERROR";
export const CLEAR_AMENIDADES_ERROR = "CLEAR_AMENIDADES_ERROR";

export const GET_AMENIDADES_SUCCESS = "GET_AMENIDADES_SUCCESS";
export const GET_TIPOS_AMENIDAD_SUCCESS = "GET_TIPOS_AMENIDAD_SUCCESS";

export const SET_SELECTED_AMENIDAD = "SET_SELECTED_AMENIDAD";
export const CREATE_AMENIDAD_SUCCESS = "CREATE_AMENIDAD_SUCCESS";
export const UPDATE_AMENIDAD_SUCCESS = "UPDATE_AMENIDAD_SUCCESS";
